import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "./components/navBar/component";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
interface layout {
	children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<layout>) {
	
	return (
		<html lang="en">
			<body>
				<NavBar/>
				<div id="root">{children}</div>
			</body>
		</html>
	);
}
